# CD pipeline
name: CD Pipeline

on:
    workflow_dispatch:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed
permissions:
  id-token: write
  contents: read   # This is required for actions/checkout@v2
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-helm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show working directory
        run: pwd
      - name: Show working directory
        run: ls

      - name: Configure AWS credentials from IAM Role (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::269633716143:role/githubChallengeRole
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Configure kubectl for EKS
        run: |
            aws eks --region us-east-1 update-kubeconfig --name app-blue-eks
            
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Update Helm values with new IMAGE_TAG
        run: |
            IMAGE_TAG=${{ github.sha }}
            echo "Updating Helm values with IMAGE_TAG: $IMAGE_TAG"
            sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|" values.yaml

      - name: Deploy with Helm
        run: |
            helm upgrade my-release . --namespace backend --values app-helm/values.yaml --install --atomic    
      
