name: DevEx Configure Namespaces

on:
  workflow_dispatch:
    inputs:
      apply:
        description: tf apply
        required: true
        default: 'false'
      environment:
        description: 'Nombre del environment (dev, staging, prod, etc.)'
        required: true
        default: 'dev'
        type: choice
        options:
            - dev
            - staging
            - prod
permissions:
  id-token: write
  contents: read   # This is required for actions/checkout@v2            
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    
    - name: Configure AWS credentials from IAM Role (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: arn:aws:iam::269633716143:role/githubChallengeRole
          role-session-name: samplerolesession
          aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: infra/terraform

    - name: Terraform Plan
      run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"
      working-directory: infra/terraform
      env:
        TF_LOG: INFO

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: ${{ github.event.inputs.apply == 'true' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Configure AWS credentials from IAM Role (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: arn:aws:iam::269633716143:role/githubChallengeRole
          role-session-name: samplerolesession
          aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: infra/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
      working-directory: infra/terraform
      env:
        TF_LOG: INFO
